# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Verb.create :base => "arise", :past => "arose", :past_particle => "arisen", :translation => "surgir, erguer-se"
Verb.create :base => "awake", :past => "awoke", :past_particle => "awoken", :translation => "despertar"
Verb.create :base => "be", :past => "was, were", :past_particle => "been", :translation => "ser, estar"
Verb.create :base => "bear", :past => "bore", :past_particle => "borne", :translation => "suportar, ser portador de"
Verb.create :base => "beat", :past => "beat", :past_particle => "beaten", :translation => "bater"
Verb.create :base => "become", :past => "became", :past_particle => "become", :translation => "tornar-se"
Verb.create :base => "befall", :past => "befell", :past_particle => "befallen", :translation => "acontecer"
Verb.create :base => "beget", :past => "begot", :past_particle => "begotten, begot", :translation => "procriar, gerar"
Verb.create :base => "begin", :past => "began", :past_particle => "begun", :translation => "começar"
Verb.create :base => "behold", :past => "beheld", :past_particle => "beheld", :translation => "contemplar"
Verb.create :base => "bend", :past => "bent", :past_particle => "bent", :translation => "curvar"
Verb.create :base => "bet", :past => "bet", :past_particle => "bet", :translation => "apostar"
Verb.create :base => "bid", :past => "bid", :past_particle => "bid", :translation => "oferecer, fazer uma oferta"
Verb.create :base => "bind", :past => "bound", :past_particle => "bound", :translation => "unir, encadernar, obrigar-se"
Verb.create :base => "bite", :past => "bit", :past_particle => "bitten", :translation => "morder"
Verb.create :base => "bleed", :past => "bled", :past_particle => "bled", :translation => "sangrar, ter hemorragia"
Verb.create :base => "blow", :past => "blew", :past_particle => "blown", :translation => "assoprar, explodir"
Verb.create :base => "break", :past => "broke", :past_particle => "broken", :translation => "quebrar"
Verb.create :base => "breed", :past => "bred", :past_particle => "bred", :translation => "procriar, reproduzir"
Verb.create :base => "bring", :past => "brought", :past_particle => "brought", :translation => "trazer"
Verb.create :base => "broadcast", :past => "broadcast", :past_particle => "broadcast", :translation => "irradiar, transmitir (sinal de rádio ou TV)"
Verb.create :base => "build", :past => "built", :past_particle => "built", :translation => "construir"
Verb.create :base => "buy", :past => "bought", :past_particle => "bought", :translation => "comprar"
Verb.create :base => "cast", :past => "cast", :past_particle => "cast", :translation => "atirar, deitar"
Verb.create :base => "catch", :past => "caught", :past_particle => "caught", :translation => "pegar, capturar"
Verb.create :base => "choose", :past => "chose", :past_particle => "chosen", :translation => "escolher"
Verb.create :base => "cling", :past => "clung", :past_particle => "clung", :translation => "aderir, segurar-se"
Verb.create :base => "come", :past => "came", :past_particle => "come", :translation => "vir"
Verb.create :base => "cost", :past => "cost", :past_particle => "cost", :translation => "custar"
Verb.create :base => "creep", :past => "crept", :past_particle => "crept", :translation => "rastejar"
Verb.create :base => "cut", :past => "cut", :past_particle => "cut", :translation => "cortar"
Verb.create :base => "deal", :past => "dealt", :past_particle => "dealt", :translation => "negociar, tratar"
Verb.create :base => "dig", :past => "dug", :past_particle => "dug", :translation => "cavocar"
Verb.create :base => "do", :past => "did", :past_particle => "done", :translation => "fazer **"
Verb.create :base => "draw", :past => "drew", :past_particle => "drawn", :translation => "tracionar, desenhar **"
Verb.create :base => "drink", :past => "drank", :past_particle => "drunk", :translation => "beber"
Verb.create :base => "drive", :past => "drove", :past_particle => "driven", :translation => "dirigir, ir de carro"
Verb.create :base => "eat", :past => "ate", :past_particle => "eaten", :translation => "comer"
Verb.create :base => "fall", :past => "fell", :past_particle => "fallen", :translation => "cair"
Verb.create :base => "feed", :past => "fed", :past_particle => "fed", :translation => "alimentar"
Verb.create :base => "feel", :past => "felt", :past_particle => "felt", :translation => "sentir, sentir-se"
Verb.create :base => "fight", :past => "fought", :past_particle => "fought", :translation => "lutar"
Verb.create :base => "find", :past => "found", :past_particle => "found", :translation => "achar, encontrar"
Verb.create :base => "flee", :past => "fled", :past_particle => "fled", :translation => "fugir, escapar"
Verb.create :base => "fling", :past => "flung", :past_particle => "flung", :translation => "arremessar"
Verb.create :base => "fly", :past => "flew", :past_particle => "flown", :translation => "voar, pilotar"
Verb.create :base => "forbid", :past => "forbade", :past_particle => "forbidden", :translation => "proibir"
Verb.create :base => "forget", :past => "forgot", :past_particle => "forgot, forgotten", :translation => "esquecer"
Verb.create :base => "forgive", :past => "forgave", :past_particle => "forgiven", :translation => "perdoar"
Verb.create :base => "freeze", :past => "froze", :past_particle => "frozen", :translation => "congelar, paralisar"
Verb.create :base => "get", :past => "got", :past_particle => "gotten, got", :translation => "obter **"
Verb.create :base => "give", :past => "gave", :past_particle => "given", :translation => "dar"
Verb.create :base => "go", :past => "went", :past_particle => "gone", :translation => "ir"
Verb.create :base => "grind", :past => "ground", :past_particle => "ground", :translation => "moer"
Verb.create :base => "grow", :past => "grew", :past_particle => "grown", :translation => "crescer, cultivar"
Verb.create :base => "have", :past => "had", :past_particle => "had", :translation => "ter, beber, comer"
Verb.create :base => "hear", :past => "heard", :past_particle => "heard", :translation => "ouvir"
Verb.create :base => "hide", :past => "hid", :past_particle => "hidden, hid", :translation => "esconder"
Verb.create :base => "hit", :past => "hit", :past_particle => "hit", :translation => "bater"
Verb.create :base => "hold", :past => "held", :past_particle => "held", :translation => "segurar"
Verb.create :base => "hurt", :past => "hurt", :past_particle => "hurt", :translation => "machucar"
Verb.create :base => "keep", :past => "kept", :past_particle => "kept", :translation => "guardar, manter"
Verb.create :base => "know", :past => "knew", :past_particle => "known", :translation => "saber, conhecer"
Verb.create :base => "lay", :past => "laid", :past_particle => "laid", :translation => "colocar em posição horizontal, assentar"
Verb.create :base => "lead", :past => "led", :past_particle => "led", :translation => "liderar"
Verb.create :base => "leave", :past => "left", :past_particle => "left", :translation => "deixar, partir"
Verb.create :base => "lend", :past => "lent", :past_particle => "lent", :translation => "dar emprestado"
Verb.create :base => "let", :past => "let", :past_particle => "let", :translation => "deixar, alugar"
Verb.create :base => "lie", :past => "lay", :past_particle => "lain", :translation => "deitar"
Verb.create :base => "lose", :past => "lost", :past_particle => "lost", :translation => "perder, extraviar"
Verb.create :base => "make", :past => "made", :past_particle => "made", :translation => "fazer, fabricar **"
Verb.create :base => "mean", :past => "meant", :past_particle => "meant", :translation => "significar, querer dizer"
Verb.create :base => "meet", :past => "met", :past_particle => "met", :translation => "encontrar, conhecer"
Verb.create :base => "overcome", :past => "overcame", :past_particle => "overcome", :translation => "superar"
Verb.create :base => "overtake", :past => "overtook", :past_particle => "overtaken", :translation => "alcançar, surpreender"
Verb.create :base => "pay", :past => "paid", :past_particle => "paid", :translation => "pagar"
Verb.create :base => "put", :past => "put", :past_particle => "put", :translation => "colocar"
Verb.create :base => "quit", :past => "quit", :past_particle => "quit", :translation => "abandonar"
Verb.create :base => "read", :past => "read", :past_particle => "read", :translation => "ler"
Verb.create :base => "ride", :past => "rode", :past_particle => "ridden", :translation => "andar (de bicicleta, moto, a cavalo)"
Verb.create :base => "ring", :past => "rang", :past_particle => "rung", :translation => "tocar (campainha, etc.)"
Verb.create :base => "rise", :past => "rose", :past_particle => "risen", :translation => "subir, erguer-se"
Verb.create :base => "run", :past => "ran", :past_particle => "run", :translation => "correr, concorrer, dirigir"
Verb.create :base => "saw", :past => "sawed", :past_particle => "sawn", :translation => "serrar"
Verb.create :base => "say", :past => "said", :past_particle => "said", :translation => "dizer"
Verb.create :base => "see", :past => "saw", :past_particle => "seen", :translation => "ver"
Verb.create :base => "seek", :past => "sought", :past_particle => "sought", :translation => "procurar obter, objetivar"
Verb.create :base => "sell", :past => "sold", :past_particle => "sold", :translation => "vender"
Verb.create :base => "send", :past => "sent", :past_particle => "sent", :translation => "mandar"
Verb.create :base => "set", :past => "set", :past_particle => "set", :translation => "pôr em determinada condição, marcar, ajustar **"
Verb.create :base => "shake", :past => "shook", :past_particle => "shaken", :translation => "sacudir, tremer"
Verb.create :base => "shed", :past => "shed", :past_particle => "shed", :translation => "soltar, deixar cair **"
Verb.create :base => "shine", :past => "shone", :past_particle => "shone", :translation => "brilhar, reluzir"
Verb.create :base => "shoot", :past => "shot", :past_particle => "shot", :translation => "atirar, disparar, alvejar, fotografar, filmar"
Verb.create :base => "show", :past => "showed", :past_particle => "shown", :translation => "mostrar, exibir"
Verb.create :base => "shrink", :past => "shrank", :past_particle => "shrunk", :translation => "encolher, contrair"
Verb.create :base => "shut", :past => "shut", :past_particle => "shut", :translation => "fechar, cerrar"
Verb.create :base => "sing", :past => "sang", :past_particle => "sung", :translation => "cantar"
Verb.create :base => "sink", :past => "sank", :past_particle => "sunk", :translation => "afundar, submergir"
Verb.create :base => "sit", :past => "sat", :past_particle => "sat", :translation => "sentar"
Verb.create :base => "slay", :past => "slew", :past_particle => "slain", :translation => "matar, assassinar"
Verb.create :base => "sleep", :past => "slept", :past_particle => "slept", :translation => "dormir"
Verb.create :base => "slide", :past => "slid", :past_particle => "slid", :translation => "deslizar, escorregar"
Verb.create :base => "sling", :past => "slung", :past_particle => "slung", :translation => "atirar, arremessar"
Verb.create :base => "speak", :past => "spoke", :past_particle => "spoken", :translation => "falar"
Verb.create :base => "spend", :past => "spent", :past_particle => "spent", :translation => "gastar"
Verb.create :base => "spin", :past => "spun", :past_particle => "spun", :translation => "fiar, rodopiar"
Verb.create :base => "spit", :past => "spit, spat", :past_particle => "spit, spat", :translation => "cuspir"
Verb.create :base => "spread", :past => "spread", :past_particle => "spread", :translation => "espalhar"
Verb.create :base => "spring", :past => "sprang", :past_particle => "sprung", :translation => "fazer saltar"
Verb.create :base => "stand", :past => "stood", :past_particle => "stood", :translation => "parar de pé, aguentar"
Verb.create :base => "steal", :past => "stole", :past_particle => "stolen", :translation => "roubar"
Verb.create :base => "stick", :past => "stuck", :past_particle => "stuck", :translation => "cravar, fincar, enfiar"
Verb.create :base => "sting", :past => "stung", :past_particle => "stung", :translation => "picar (inseto)"
Verb.create :base => "stink", :past => "stank", :past_particle => "stunk", :translation => "cheirar mal"
Verb.create :base => "strike", :past => "struck", :past_particle => "struck", :translation => "golpear, desferir, atacar"
Verb.create :base => "string", :past => "strung", :past_particle => "strung", :translation => "encordoar, amarrar"
Verb.create :base => "strive", :past => "strove", :past_particle => "striven", :translation => "esforçar-se, lutar"
Verb.create :base => "swear", :past => "swore", :past_particle => "sworn", :translation => "jurar, prometer, assegurar"
Verb.create :base => "sweep", :past => "swept", :past_particle => "swept", :translation => "varrer"
Verb.create :base => "swim", :past => "swam", :past_particle => "swum", :translation => "nadar"
Verb.create :base => "swing", :past => "swung", :past_particle => "swung", :translation => "balançar, alternar"
Verb.create :base => "take", :past => "took", :past_particle => "taken", :translation => "tomar **"
Verb.create :base => "teach", :past => "taught", :past_particle => "taught", :translation => "ensinar, dar aula"
Verb.create :base => "tear", :past => "tore", :past_particle => "torn", :translation => "rasgar, despedaçar"
Verb.create :base => "tell", :past => "told", :past_particle => "told", :translation => "dizer, contar"
Verb.create :base => "think", :past => "thought", :past_particle => "thought", :translation => "pensar"
Verb.create :base => "throw", :past => "threw", :past_particle => "thrown", :translation => "atirar, arremessar"
Verb.create :base => "tread", :past => "trod", :past_particle => "trodden", :translation => "pisar, trilhar"
Verb.create :base => "undergo", :past => "underwent", :past_particle => "undergone", :translation => "submeter-se a, suportar"
Verb.create :base => "understand", :past => "understood", :past_particle => "understood", :translation => "entender"
Verb.create :base => "uphold", :past => "upheld", :past_particle => "upheld", :translation => "sustentar, apoiar, defender"
Verb.create :base => "wear", :past => "wore", :past_particle => "worn", :translation => "vestir, usar, gastar"
Verb.create :base => "win", :past => "won", :past_particle => "won", :translation => "vencer, ganhar"
Verb.create :base => "wind", :past => "wound", :past_particle => "wound", :translation => "enrolar, rodar, dar corda"
Verb.create :base => "write", :past => "wrote", :past_particle => "written", :translation => "escrever, redigir"